---
title: "normal marker check"
output: html_notebook
---

need to load Yangyi's marker
```{r}
library(Seurat)
library(dplyr)
library(patchwork)
normal <- readRDS("~/CASCADEpaper/paper/Fig2/normal_cells/normal_harmony_srt.Rds")

```

```{r}
DimPlot(normal,label = T) 
DimPlot(normal, group.by = "patient")
FeaturePlot(normal, "AR")
DimPlot(normal, group.by = "Cell.Identity")
DimPlot(normal, group.by = "max_id")
```


```{r}
normal <- AddModuleScore(normal, features = list(genelist$cancer))
FeaturePlot(normal, "Cluster1")
```

## Epithelial cells
```{r}
FeaturePlot(normal, Epithelial_feature)
DotPlot(normal, features = Epithelial_feature)
```
XBP1 could be cancer marker, KLK3 is PSA level 

```{r}
FeaturePlot(normal, Endothelial_feature)
DotPlot(normal, features = Endothelial_feature)
```
```{r}
FeaturePlot(normal, Fibroblast_feature)
DotPlot(normal, features = Fibroblast_feature)
```
suddenly find include CA76 tumor, all the neuron should be tumors
then it is pretty clear through the infercnv then

```{r}
library(phylogram)
library(dendextend)
dend <- read.dendrogram("~/CASCADEpaper/paper/Fig2/normal_cells/infercnv/unclustered/infercnv.preliminary.observations_dendrogram.txt")
dend <- color_branches(dend, h = 100)
plot(dend)
```
```{r}
FeaturePlot(normal_clean, Endothelial_feature)
DotPlot(normal_clean, features = Endothelial_feature)
FeaturePlot(normal_clean, Epithelial_feature)
DotPlot(normal_clean, features = Epithelial_feature)
FeaturePlot(normal_clean, Fibroblast_feature)
DotPlot(normal_clean, features = Fibroblast_feature)
DotPlot(normal_clean, features = focused_B_cell_feature)
DotPlot(normal_clean, features = focused_T_cell_feature)
```
```{r}
DotPlot(normal_clean, features = Macrophage_feature) + theme(axis.text.x = element_text(angle = 90))
DotPlot(normal_clean, features = Plasma_cell_feature) + theme(axis.text.x = element_text(angle = 90))
```

```{r}
library(readxl)
markers <- read_excel("encyclopedia_table.xlsx", sheet = 1)
genes <- strsplit(markers$`Curated markers`, split = ",")
genes <- lapply(genes, function(x){
   temp <- gsub("^ ", "", x)
   temp <- temp[temp %in% rownames(normal_clean2)]
  })
names(genes) <- markers$`Low-hierarchy cell types`
library(patchwork)
genes <- genes[sapply(genes, length)>0]
```

```{r fig.height=10, fig.width=10}
DimPlot(normal_clean2, label = T)
DimPlot(normal_clean2, group.by = "max_id")
for (i in names(genes)){
f <- FeaturePlot(normal_clean2, genes[[i]]) + plot_annotation(title = i)
print(f)  
}
```

```{r fig.height=10, fig.width=10}
FeaturePlot(normal_clean2, angiogenesis_feature)
```

```{r}
all_featurelist <- list(Macrophage_feature, Monocyte_feature, CD4_T_cell_feature, CD8_T_cell_feature,
NK_feature, Fibroblast_feature, Plasma_cell_feature, B_cell_feature, Endothelial_feature,
Epithelial_feature, Mast_feature, pDC_feature, mDC_feature)

all_features <- lapply(all_featurelist, function(x){
  temp <- x[x%in% rownames(normal_clean2)]
  if(length(temp) > 1){
  temp <- temp[apply(normal_clean2[["RNA"]]@counts[temp, ],1, function(y) sum(y > 0)>10)]
  return(temp)
  }else(
    return(NULL)
  )
})
all_features <- all_features[sapply(all_features, length)>0]

lapply(all_features, function(x) FeaturePlot(normal_clean2, x))
```
```{r fig.height=8, fig.width=8}
for ( i in names(test)){
  f <- FeaturePlot(normal_clean2, features = test[[i]]$`Gene name`, cols = rev(brewer.rdylbu(5))) + plot_annotation(title  = i)
  print(f)
}
```

