library(reticulate)
library(Rmagic)
library(scATOMIC)
library(plyr)
library(dplyr)
library(data.table)
library(randomForest)
library(caret)
library(parallel)
library(reticulate)
library(Rmagic)
library(Matrix)
library(Seurat)
library(agrmt)
library(cutoff.scATOMIC)
library(ggplot2)

srt <- readRDS("~/normal_cell_annotation/normal_cluster_srt.Rds")

sparse_matrix <- srt@assays$RNA@counts
cell_predictions <- run_scATOMIC(sparse_matrix)
saveRDS(cell_predictions, "~/normal_cell_annotation/scATOMIC_cellpred.Rds")
results_cell <- create_summary_matrix(prediction_list = cell_predictions, use_CNVs = F, modify_results = T, mc.cores = 6, raw_counts = sparse_matrix, min_prop = 0.5, known_cancer_type = "PRAD")
saveRDS(results_cell, "~/normal_cell_annotation/scATOMIC_result.Rds")